### ISSUE TITLE
Add expanded / expanded if applicable fields to schema

### ISSUE THREAD

**Issue by benbalter** [project-open-data/catalog-generator#11]
https://github.com/project-open-data/catalog-generator/blob/gh-pages/_includes/schema.yml

**Comment by gbinal** [comment]
Sure thing - is this a blocker in the meantime?

**Comment by gbinal** [comment]
Done

**Comment by gbinal** [comment]
P.S.  Note layout of 'if_applicable' and expanded - hope that's okay.
