### ISSUE TITLE
Raptor should take bite out of Executive Seal

### ISSUE THREAD

**Issue by greggersh** [project-open-data/catalog-generator#17]
What?  What raptor?

**Comment by dannychapman** [comment]
Yes.

**Comment by greggersh** [comment]
I know, right?  Seals are delicious.

**Comment by waldoj** [comment]
Please tell me Randy has something to do with this.

**Comment by gbinal** [comment]
So.... fair point but I'm going to go ahead and close this issue for now.  Good food for thought.  :)
