### ISSUE TITLE
Update Schema

### ISSUE THREAD

**Issue by benbalter** [project-open-data/catalog-generator#18]
[schema.yml](https://github.com/project-open-data/catalog-generator/blob/gh-pages/schema.yml) need to be updated to sync with [the connonical version](http://project-open-data.github.io/schema/).

Related, https://github.com/project-open-data/json-validator/issues/2, needs an update as well.

To my knowledge there is no up to date machine readable version of the schema.

/cc @gbinal @feomike @waldoj @haleyvandyck

**Comment by gbinal** [comment]
Thanks, Ben.  Working on it.

**Comment by feomike** [comment]
+1 - excellent, thanks!

**Comment by cew821** [comment]
I'm going to dive in on this one, hopefully have something on it later this week.

**Comment by gbinal** [comment]
Thanks a ton!  Sorry I haven't gotten to yet.  

G
