### ISSUE TITLE
hosted version is down

### ISSUE THREAD

**Issue by gbinal** [project-open-data/catalog-generator#2]
http://project-open-data.github.com/catalog-generator/ is returning a 404 for me.  Unfortunately, I need to confirm the link for labs.data.gov.  A) Ben, can you help me get it back up and/or B)If not, can we confirm that the hosted variant will be live again at that link?

**Comment by benbalter** [comment]
2cf3db12c63b2ec591986d9928a85e41b16c74aa fixes, props @gbinal.

Problem was changes to core repository required sub repos to be rebuilt.
