### ISSUE TITLE
Add New Dataset causes too many extra fields and erases existing information

### ISSUE THREAD

**Issue by gbinal** [project-open-data/catalog-generator#4]
If one begins using the generator and inputs the information for the first data set, then clicks 'Add New Dataset', the existing information that had been typed in for the first dataset is lost.  

A second problem is that the resulting fields are duplicated (e.g. the new data set has two sets of overlapping metadata; and if I click 'add new dataset' again, then a triplicate set of overlapping metadata results).  

![catalog generator 3](https://f.cloud.github.com/assets/633088/104298/27f0108c-6980-11e2-92c7-b0da67f55bc3.JPG)

**Comment by benbalter** [comment]
Thank you for taking the time to file an issue, however I believe you are describing two distinct issues. 

If that is in fact the case, please submit them as two issues so that their status can be more accurately tracked.
