### ISSUE TITLE
Add New Dataset causes too many extra fields

### ISSUE THREAD

**Issue by gbinal** [project-open-data/catalog-generator#8]
If one begins using the generator and inputs the information for the first data set, then clicks 'Add New Dataset',  the resulting fields are duplicated (e.g. the new data set has two sets of overlapping metadata; and if I click 'add new dataset' again, then a triplicate set of overlapping metadata results).  

![catalog generator 3](https://f.cloud.github.com/assets/633088/104298/27f0108c-6980-11e2-92c7-b0da67f55bc3.JPG)

**Comment by benbalter** [comment]
951a06f56f76d1a3a7ca5c706cc73e5367df844f fixes.
